create table revenue(
    id serial primary key,
    account varchar not null,
    amount double not null,
    device varchar(5) not null,
    categories varchar not null,
    labels varchar,
    "date"  date(now()),
    "hour" time(now()),
    payer varchar,
    note varchar,
    payment_method varchar not null,
    payment_status varchar not null,
    location varchar,
);